exclude_paths:
  # Excludes the source directory where these formatting issues are occurring
  - "src/**"
  # Excludes the build configuration file shown in the diff
  - "rollup.config.mjs"

engines:
  # Disables duplication checks for these files specifically
  duplication:
    exclude_paths:
      - "src/**"
  
  # Disables code patterns/linting checks (like quote and space rules)
  codacy-cs-shorthand:
    exclude_paths:
      - "src/**"

  # If you are using ESLint or similar for the JS/TS files
  eslint:
    exclude_paths:
      - "src/**"