language:
  - node_js

notifications:
    slack:
        rooms:
            - cognitivevr:HHACAo19lTRQXZWblbfGaL36
        on_success: change
        on_failure: change
    email:
        recipients:
            - engineering@cognitive3d.com
    on_success: always
    on_failure: always
